// Guest Message Submission Contract
// Defines the shape and rules for guest message submissions and display

/**
 * GuestMessageSubmission
 * A public guest message record persisted in the database
 */
export interface GuestMessageSubmission {
    id: string; // UUID, generated by Supabase
    guestName: string; // Author's name (1-100 chars, trimmed, non-empty)
    message: string; // Message text (1-500 chars, trimmed, non-empty)
    approved: boolean; // Moderation flag (defaults to true)
    createdAt: string; // ISO 8601 timestamp of submission
}

/**
 * MessageCard
 * Rendered visual representation of a guest message
 */
export interface MessageCard {
    id: string; // Reference to GuestMessageSubmission.id
    guestName: string; // Guest name from submission
    message: string; // Message text from submission
    displayRotation: number; // CSS rotation in degrees (±1-3)
    displayColor?: string; // Tailwind color class for card background
    createdAt: string; // From submission
    displayOrder?: number; // Grid placement order
}

/**
 * GuestMessageFormInput
 * Client-side form input for message submission
 */
export interface GuestMessageFormInput {
    guestName: string; // Raw user input for guest name
    message: string; // Raw user input for message
}

/**
 * GuestMessageFormState
 * Current state of message submission form UI
 */
export interface GuestMessageFormState {
    guestName: string; // Form input value
    message: string; // Form input value
    isValidating: boolean; // Client-side validation in progress
    errors: {
        guestName?: string; // Field-level error for name
        message?: string; // Field-level error for message
    };
    isSubmitting: boolean; // API request in progress
    isSuccess: boolean; // Submission succeeded (auto-clears after 3 seconds)
    successMessage: string; // Success feedback message
}

/**
 * GuestMessageSubmissionRequest
 * Payload for POST /api/guest-message
 */
export interface GuestMessageSubmissionRequest {
    guestName: string; // Guest name
    message: string; // Message text
}

/**
 * GuestMessageSubmissionResponse
 * Response from POST /api/guest-message
 */
export interface GuestMessageSubmissionResponse {
    success: boolean;
    data?: GuestMessageSubmission;
    error?: string;
}

/**
 * GuestMessageListResponse
 * Response from GET /api/guest-messages (approved messages only)
 */
export interface GuestMessageListResponse {
    messages: GuestMessageSubmission[];
    count: number;
}

/**
 * MessageWallState
 * State of the messages page/display wall
 */
export interface MessageWallState {
    cards: MessageCard[];
    isLoading: boolean;
    error: string | null;
    isEmpty: boolean; // True if no approved messages
}

// Validation Rules (enforced in implementation)
export const GuestMessageValidation = {
    submission: {
        guestName: {
            required: true,
            minLength: 1,
            maxLength: 100,
            trim: true,
            pattern: /\S/, // Must contain non-whitespace
        },
        message: {
            required: true,
            minLength: 1,
            maxLength: 500,
            trim: true,
            pattern: /\S/, // Must contain non-whitespace
        },
    },
    formInput: {
        guestName: {
            required: true,
            minLength: 1,
            maxLength: 100,
        },
        message: {
            required: true,
            minLength: 1,
            maxLength: 500,
        },
    },
} as const;

// Constraints
export const GuestMessageConstraints = {
    maxMessageLength: 500,
    maxNameLength: 100,
    minNameLength: 1,
    minMessageLength: 1,
    requestTimeout: 10000, // API request timeout (ms)
    successMessageDuration: 3000, // How long success message displays (ms)
    cardRotationRange: 3, // ±3 degrees max rotation for playful effect
    gridColumnsResponsive: {
        mobile: 1,
        tablet: 2,
        desktop: 3,
    },
} as const;

// Error Messages
export const GuestMessageErrorMessages = {
    guestNameRequired: "Please enter your name.",
    guestNameInvalid: "Please enter a valid name (1-100 characters).",
    messageRequired: "Please write a message.",
    messageInvalid: "Message must be between 1 and 500 characters.",
    messageEmpty: "Message cannot be empty or contain only spaces.",
    submissionFailed: "Failed to post your message. Please try again.",
    networkError: "Network error. Please check your connection and retry.",
} as const;

// Success Messages
export const GuestMessageSuccessMessages = {
    submitted: "Your message has been posted to the wall!",
    default: "Thank you for leaving a message!",
} as const;

// Empty State Messages
export const GuestMessageEmptyStateMessages = {
    title: "No messages yet",
    subtitle: "Be the first to leave a farewell message!",
    cta: "Share your thoughts",
} as const;
