// RSVP Submission Contract
// Defines the shape and rules for RSVP form submissions and data persistence

/**
 * RSVPSubmission
 * A guest attendance confirmation record
 */
export interface RSVPSubmission {
    id: string; // UUID, generated by Supabase
    name: string; // Guest's submitted name (1-100 chars, trimmed, non-empty)
    confirmedAt: string; // ISO 8601 timestamp of submission
    createdAt: string; // ISO 8601 timestamp of record creation
    status: "confirmed" | "pending"; // Confirmation status (defaults to "confirmed")
}

/**
 * RSVPFormInput
 * Client-side form input for RSVP submission
 */
export interface RSVPFormInput {
    name: string; // Raw user input
}

/**
 * RSVPFormState
 * Current state of RSVP form UI
 */
export interface RSVPFormState {
    name: string; // Form input value
    isValidating: boolean; // Client-side validation in progress
    error: string | null; // Validation or submission error message
    isSubmitting: boolean; // API request in progress
    isSuccess: boolean; // Submission succeeded (auto-clears after 3 seconds)
    successMessage: string; // Success feedback message
}

/**
 * RSVPSubmissionRequest
 * Payload for POST /api/guest-rsvp
 */
export interface RSVPSubmissionRequest {
    name: string; // Guest name to submit
}

/**
 * RSVPSubmissionResponse
 * Response from POST /api/guest-rsvp
 */
export interface RSVPSubmissionResponse {
    success: boolean;
    data?: RSVPSubmission;
    error?: string;
}

/**
 * RSVPListResponse
 * Response from GET /api/guest-rsvps (read-only, admin access)
 */
export interface RSVPListResponse {
    rsvps: RSVPSubmission[];
    count: number;
}

// Validation Rules (enforced in implementation)
export const RSVPValidation = {
    submission: {
        name: {
            required: true,
            minLength: 1,
            maxLength: 100,
            trim: true,
            pattern: /\S/, // Must contain non-whitespace
        },
    },
    formInput: {
        name: {
            required: true,
            minLength: 1,
            maxLength: 100,
            // Validation runs: trim, check non-empty
        },
    },
} as const;

// Constraints
export const RSVPConstraints = {
    requestTimeout: 10000, // API request timeout (ms)
    successMessageDuration: 3000, // How long success message displays (ms)
    allowDuplicateNames: true, // Spec: may accept duplicate names
} as const;

// Error Messages
export const RSVPErrorMessages = {
    nameRequired: "Please enter your name to confirm attendance.",
    nameInvalid: "Please enter a valid name (1-100 characters).",
    submissionFailed: "Failed to submit RSVP. Please try again.",
    networkError: "Network error. Please check your connection and retry.",
} as const;

// Success Messages
export const RSVPSuccessMessages = {
    submitted: "Your RSVP is confirmed! We'll see you soon.",
    default: "Thank you for confirming your attendance!",
} as const;
